language: go

matrix:
  include:
    - go: 1.11.x
    - go: tip
  allow_failures:
    - go: tip

notifications:
  email: false

before_install:
  - sudo apt-get update -q
  - sudo apt-get install -y gcc libkrb5-dev

script: make
